import { NavBar } from "navbar.slint";
import { SettingsPage } from "settings.slint";
import { StaticPage } from "static.slint";
import { LivePage } from "live.slint";
import { AppStore } from "store.slint";

export { AppStore }

export component MainWindow inherits Window {
    title: "RexPaper";
    icon: @image-url("../assets/logo.png");
    
    min-height: 720px;
    min-width: 1280px;
    background: #f0f0f0;
  
    in-out property <string> active-page: "static";

    HorizontalLayout {
    
        NavBar {
            active-page: root.active-page;
            page-selected(page-name) => {
                root.active-page = page-name;
            }
        }
        
        // THE FIX: Use a Layout primitive instead of a Rectangle
        VerticalLayout {
            horizontal-stretch: 1;
            
            // THE FIX: Remove manual sizes. The layout stretches them automatically!
            if root.active-page == "settings" : SettingsPage {}
            if root.active-page == "static" : StaticPage {}
            if root.active-page == "live" : LivePage {}
        }
    }
}